# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "The Exegesist"
email: "jamesrcrooke@gmail.com"
description: "Bringing darkness to light, The Exegesist exists to explore sophisticated horror and its message about the human condition, or more accurately, human abberation." 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doulosiyxy.github.io/theexegesist" # the base hostname & protocol for your site
github_username: "doulosiyxy" 

# Build settings
markdown: kramdown
